require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CommissionClaimStatusesController do

  # This should return the minimal set of attributes required to create a valid
  # CommissionClaimStatus. As you add validations to CommissionClaimStatus, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CommissionClaimStatusesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all commission_claim_statuses as @commission_claim_statuses" do
      commission_claim_status = CommissionClaimStatus.create! valid_attributes
      get :index, {}, valid_session
      assigns(:commission_claim_statuses).should eq([commission_claim_status])
    end
  end

  describe "GET show" do
    it "assigns the requested commission_claim_status as @commission_claim_status" do
      commission_claim_status = CommissionClaimStatus.create! valid_attributes
      get :show, {:id => commission_claim_status.to_param}, valid_session
      assigns(:commission_claim_status).should eq(commission_claim_status)
    end
  end

  describe "GET new" do
    it "assigns a new commission_claim_status as @commission_claim_status" do
      get :new, {}, valid_session
      assigns(:commission_claim_status).should be_a_new(CommissionClaimStatus)
    end
  end

  describe "GET edit" do
    it "assigns the requested commission_claim_status as @commission_claim_status" do
      commission_claim_status = CommissionClaimStatus.create! valid_attributes
      get :edit, {:id => commission_claim_status.to_param}, valid_session
      assigns(:commission_claim_status).should eq(commission_claim_status)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CommissionClaimStatus" do
        expect {
          post :create, {:commission_claim_status => valid_attributes}, valid_session
        }.to change(CommissionClaimStatus, :count).by(1)
      end

      it "assigns a newly created commission_claim_status as @commission_claim_status" do
        post :create, {:commission_claim_status => valid_attributes}, valid_session
        assigns(:commission_claim_status).should be_a(CommissionClaimStatus)
        assigns(:commission_claim_status).should be_persisted
      end

      it "redirects to the created commission_claim_status" do
        post :create, {:commission_claim_status => valid_attributes}, valid_session
        response.should redirect_to(CommissionClaimStatus.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved commission_claim_status as @commission_claim_status" do
        # Trigger the behavior that occurs when invalid params are submitted
        CommissionClaimStatus.any_instance.stub(:save).and_return(false)
        post :create, {:commission_claim_status => { "name" => "invalid value" }}, valid_session
        assigns(:commission_claim_status).should be_a_new(CommissionClaimStatus)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CommissionClaimStatus.any_instance.stub(:save).and_return(false)
        post :create, {:commission_claim_status => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested commission_claim_status" do
        commission_claim_status = CommissionClaimStatus.create! valid_attributes
        # Assuming there are no other commission_claim_statuses in the database, this
        # specifies that the CommissionClaimStatus created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CommissionClaimStatus.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => commission_claim_status.to_param, :commission_claim_status => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested commission_claim_status as @commission_claim_status" do
        commission_claim_status = CommissionClaimStatus.create! valid_attributes
        put :update, {:id => commission_claim_status.to_param, :commission_claim_status => valid_attributes}, valid_session
        assigns(:commission_claim_status).should eq(commission_claim_status)
      end

      it "redirects to the commission_claim_status" do
        commission_claim_status = CommissionClaimStatus.create! valid_attributes
        put :update, {:id => commission_claim_status.to_param, :commission_claim_status => valid_attributes}, valid_session
        response.should redirect_to(commission_claim_status)
      end
    end

    describe "with invalid params" do
      it "assigns the commission_claim_status as @commission_claim_status" do
        commission_claim_status = CommissionClaimStatus.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CommissionClaimStatus.any_instance.stub(:save).and_return(false)
        put :update, {:id => commission_claim_status.to_param, :commission_claim_status => { "name" => "invalid value" }}, valid_session
        assigns(:commission_claim_status).should eq(commission_claim_status)
      end

      it "re-renders the 'edit' template" do
        commission_claim_status = CommissionClaimStatus.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CommissionClaimStatus.any_instance.stub(:save).and_return(false)
        put :update, {:id => commission_claim_status.to_param, :commission_claim_status => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested commission_claim_status" do
      commission_claim_status = CommissionClaimStatus.create! valid_attributes
      expect {
        delete :destroy, {:id => commission_claim_status.to_param}, valid_session
      }.to change(CommissionClaimStatus, :count).by(-1)
    end

    it "redirects to the commission_claim_statuses list" do
      commission_claim_status = CommissionClaimStatus.create! valid_attributes
      delete :destroy, {:id => commission_claim_status.to_param}, valid_session
      response.should redirect_to(commission_claim_statuses_url)
    end
  end

end
