require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProgressionStatusesController do

  # This should return the minimal set of attributes required to create a valid
  # ProgressionStatus. As you add validations to ProgressionStatus, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProgressionStatusesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all progression_statuses as @progression_statuses" do
      progression_status = ProgressionStatus.create! valid_attributes
      get :index, {}, valid_session
      assigns(:progression_statuses).should eq([progression_status])
    end
  end

  describe "GET show" do
    it "assigns the requested progression_status as @progression_status" do
      progression_status = ProgressionStatus.create! valid_attributes
      get :show, {:id => progression_status.to_param}, valid_session
      assigns(:progression_status).should eq(progression_status)
    end
  end

  describe "GET new" do
    it "assigns a new progression_status as @progression_status" do
      get :new, {}, valid_session
      assigns(:progression_status).should be_a_new(ProgressionStatus)
    end
  end

  describe "GET edit" do
    it "assigns the requested progression_status as @progression_status" do
      progression_status = ProgressionStatus.create! valid_attributes
      get :edit, {:id => progression_status.to_param}, valid_session
      assigns(:progression_status).should eq(progression_status)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProgressionStatus" do
        expect {
          post :create, {:progression_status => valid_attributes}, valid_session
        }.to change(ProgressionStatus, :count).by(1)
      end

      it "assigns a newly created progression_status as @progression_status" do
        post :create, {:progression_status => valid_attributes}, valid_session
        assigns(:progression_status).should be_a(ProgressionStatus)
        assigns(:progression_status).should be_persisted
      end

      it "redirects to the created progression_status" do
        post :create, {:progression_status => valid_attributes}, valid_session
        response.should redirect_to(ProgressionStatus.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved progression_status as @progression_status" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProgressionStatus.any_instance.stub(:save).and_return(false)
        post :create, {:progression_status => { "name" => "invalid value" }}, valid_session
        assigns(:progression_status).should be_a_new(ProgressionStatus)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProgressionStatus.any_instance.stub(:save).and_return(false)
        post :create, {:progression_status => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested progression_status" do
        progression_status = ProgressionStatus.create! valid_attributes
        # Assuming there are no other progression_statuses in the database, this
        # specifies that the ProgressionStatus created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProgressionStatus.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => progression_status.to_param, :progression_status => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested progression_status as @progression_status" do
        progression_status = ProgressionStatus.create! valid_attributes
        put :update, {:id => progression_status.to_param, :progression_status => valid_attributes}, valid_session
        assigns(:progression_status).should eq(progression_status)
      end

      it "redirects to the progression_status" do
        progression_status = ProgressionStatus.create! valid_attributes
        put :update, {:id => progression_status.to_param, :progression_status => valid_attributes}, valid_session
        response.should redirect_to(progression_status)
      end
    end

    describe "with invalid params" do
      it "assigns the progression_status as @progression_status" do
        progression_status = ProgressionStatus.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProgressionStatus.any_instance.stub(:save).and_return(false)
        put :update, {:id => progression_status.to_param, :progression_status => { "name" => "invalid value" }}, valid_session
        assigns(:progression_status).should eq(progression_status)
      end

      it "re-renders the 'edit' template" do
        progression_status = ProgressionStatus.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProgressionStatus.any_instance.stub(:save).and_return(false)
        put :update, {:id => progression_status.to_param, :progression_status => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested progression_status" do
      progression_status = ProgressionStatus.create! valid_attributes
      expect {
        delete :destroy, {:id => progression_status.to_param}, valid_session
      }.to change(ProgressionStatus, :count).by(-1)
    end

    it "redirects to the progression_statuses list" do
      progression_status = ProgressionStatus.create! valid_attributes
      delete :destroy, {:id => progression_status.to_param}, valid_session
      response.should redirect_to(progression_statuses_url)
    end
  end

end
