require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RequiredDocTypesController do

  # This should return the minimal set of attributes required to create a valid
  # RequiredDocType. As you add validations to RequiredDocType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RequiredDocTypesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all required_doc_types as @required_doc_types" do
      required_doc_type = RequiredDocType.create! valid_attributes
      get :index, {}, valid_session
      assigns(:required_doc_types).should eq([required_doc_type])
    end
  end

  describe "GET show" do
    it "assigns the requested required_doc_type as @required_doc_type" do
      required_doc_type = RequiredDocType.create! valid_attributes
      get :show, {:id => required_doc_type.to_param}, valid_session
      assigns(:required_doc_type).should eq(required_doc_type)
    end
  end

  describe "GET new" do
    it "assigns a new required_doc_type as @required_doc_type" do
      get :new, {}, valid_session
      assigns(:required_doc_type).should be_a_new(RequiredDocType)
    end
  end

  describe "GET edit" do
    it "assigns the requested required_doc_type as @required_doc_type" do
      required_doc_type = RequiredDocType.create! valid_attributes
      get :edit, {:id => required_doc_type.to_param}, valid_session
      assigns(:required_doc_type).should eq(required_doc_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RequiredDocType" do
        expect {
          post :create, {:required_doc_type => valid_attributes}, valid_session
        }.to change(RequiredDocType, :count).by(1)
      end

      it "assigns a newly created required_doc_type as @required_doc_type" do
        post :create, {:required_doc_type => valid_attributes}, valid_session
        assigns(:required_doc_type).should be_a(RequiredDocType)
        assigns(:required_doc_type).should be_persisted
      end

      it "redirects to the created required_doc_type" do
        post :create, {:required_doc_type => valid_attributes}, valid_session
        response.should redirect_to(RequiredDocType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved required_doc_type as @required_doc_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        RequiredDocType.any_instance.stub(:save).and_return(false)
        post :create, {:required_doc_type => {  }}, valid_session
        assigns(:required_doc_type).should be_a_new(RequiredDocType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RequiredDocType.any_instance.stub(:save).and_return(false)
        post :create, {:required_doc_type => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested required_doc_type" do
        required_doc_type = RequiredDocType.create! valid_attributes
        # Assuming there are no other required_doc_types in the database, this
        # specifies that the RequiredDocType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RequiredDocType.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => required_doc_type.to_param, :required_doc_type => { "these" => "params" }}, valid_session
      end

      it "assigns the requested required_doc_type as @required_doc_type" do
        required_doc_type = RequiredDocType.create! valid_attributes
        put :update, {:id => required_doc_type.to_param, :required_doc_type => valid_attributes}, valid_session
        assigns(:required_doc_type).should eq(required_doc_type)
      end

      it "redirects to the required_doc_type" do
        required_doc_type = RequiredDocType.create! valid_attributes
        put :update, {:id => required_doc_type.to_param, :required_doc_type => valid_attributes}, valid_session
        response.should redirect_to(required_doc_type)
      end
    end

    describe "with invalid params" do
      it "assigns the required_doc_type as @required_doc_type" do
        required_doc_type = RequiredDocType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RequiredDocType.any_instance.stub(:save).and_return(false)
        put :update, {:id => required_doc_type.to_param, :required_doc_type => {  }}, valid_session
        assigns(:required_doc_type).should eq(required_doc_type)
      end

      it "re-renders the 'edit' template" do
        required_doc_type = RequiredDocType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RequiredDocType.any_instance.stub(:save).and_return(false)
        put :update, {:id => required_doc_type.to_param, :required_doc_type => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested required_doc_type" do
      required_doc_type = RequiredDocType.create! valid_attributes
      expect {
        delete :destroy, {:id => required_doc_type.to_param}, valid_session
      }.to change(RequiredDocType, :count).by(-1)
    end

    it "redirects to the required_doc_types list" do
      required_doc_type = RequiredDocType.create! valid_attributes
      delete :destroy, {:id => required_doc_type.to_param}, valid_session
      response.should redirect_to(required_doc_types_url)
    end
  end

end
