require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SlidingScalesController do

  # This should return the minimal set of attributes required to create a valid
  # SlidingScale. As you add validations to SlidingScale, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SlidingScalesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all sliding_scales as @sliding_scales" do
      sliding_scale = SlidingScale.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sliding_scales).should eq([sliding_scale])
    end
  end

  describe "GET show" do
    it "assigns the requested sliding_scale as @sliding_scale" do
      sliding_scale = SlidingScale.create! valid_attributes
      get :show, {:id => sliding_scale.to_param}, valid_session
      assigns(:sliding_scale).should eq(sliding_scale)
    end
  end

  describe "GET new" do
    it "assigns a new sliding_scale as @sliding_scale" do
      get :new, {}, valid_session
      assigns(:sliding_scale).should be_a_new(SlidingScale)
    end
  end

  describe "GET edit" do
    it "assigns the requested sliding_scale as @sliding_scale" do
      sliding_scale = SlidingScale.create! valid_attributes
      get :edit, {:id => sliding_scale.to_param}, valid_session
      assigns(:sliding_scale).should eq(sliding_scale)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SlidingScale" do
        expect {
          post :create, {:sliding_scale => valid_attributes}, valid_session
        }.to change(SlidingScale, :count).by(1)
      end

      it "assigns a newly created sliding_scale as @sliding_scale" do
        post :create, {:sliding_scale => valid_attributes}, valid_session
        assigns(:sliding_scale).should be_a(SlidingScale)
        assigns(:sliding_scale).should be_persisted
      end

      it "redirects to the created sliding_scale" do
        post :create, {:sliding_scale => valid_attributes}, valid_session
        response.should redirect_to(SlidingScale.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sliding_scale as @sliding_scale" do
        # Trigger the behavior that occurs when invalid params are submitted
        SlidingScale.any_instance.stub(:save).and_return(false)
        post :create, {:sliding_scale => {  }}, valid_session
        assigns(:sliding_scale).should be_a_new(SlidingScale)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SlidingScale.any_instance.stub(:save).and_return(false)
        post :create, {:sliding_scale => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sliding_scale" do
        sliding_scale = SlidingScale.create! valid_attributes
        # Assuming there are no other sliding_scales in the database, this
        # specifies that the SlidingScale created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SlidingScale.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => sliding_scale.to_param, :sliding_scale => { "these" => "params" }}, valid_session
      end

      it "assigns the requested sliding_scale as @sliding_scale" do
        sliding_scale = SlidingScale.create! valid_attributes
        put :update, {:id => sliding_scale.to_param, :sliding_scale => valid_attributes}, valid_session
        assigns(:sliding_scale).should eq(sliding_scale)
      end

      it "redirects to the sliding_scale" do
        sliding_scale = SlidingScale.create! valid_attributes
        put :update, {:id => sliding_scale.to_param, :sliding_scale => valid_attributes}, valid_session
        response.should redirect_to(sliding_scale)
      end
    end

    describe "with invalid params" do
      it "assigns the sliding_scale as @sliding_scale" do
        sliding_scale = SlidingScale.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SlidingScale.any_instance.stub(:save).and_return(false)
        put :update, {:id => sliding_scale.to_param, :sliding_scale => {  }}, valid_session
        assigns(:sliding_scale).should eq(sliding_scale)
      end

      it "re-renders the 'edit' template" do
        sliding_scale = SlidingScale.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SlidingScale.any_instance.stub(:save).and_return(false)
        put :update, {:id => sliding_scale.to_param, :sliding_scale => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sliding_scale" do
      sliding_scale = SlidingScale.create! valid_attributes
      expect {
        delete :destroy, {:id => sliding_scale.to_param}, valid_session
      }.to change(SlidingScale, :count).by(-1)
    end

    it "redirects to the sliding_scales list" do
      sliding_scale = SlidingScale.create! valid_attributes
      delete :destroy, {:id => sliding_scale.to_param}, valid_session
      response.should redirect_to(sliding_scales_url)
    end
  end

end
